In [1]:
import pandas as pd

In [4]:
data={'Index':[1,2,3,4,5,6,7,8,9,10]
    ,'Name':['Paul','Palak','Jason','Bobby','Alicya','Hary','Omisha','Lucy','Jayesh','Radha']
      ,'Age':[10,11,12,13,14,15,16,25,14,13],
      'Class':[10,10,9,12,8,7,6,5,7,8]
      ,'Gender':['M','F','M','M','F','M','M','M','M','F'],
      }
df= pd.DataFrame(data)

In [5]:
df

   Index    Name  Age  Class Gender
0      1    Paul   10     10      M
1      2   Palak   11     10      F
2      3   Jason   12      9      M
3      4   Bobby   13     12      M
4      5  Alicya   14      8      F
5      6    Hary   15      7      M
6      7  Omisha   16      6      M
7      8    Lucy   25      5      M
8      9  Jayesh   14      7      M
9     10   Radha   13      8      F

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Index   10 non-null     int64
 1   Name    10 non-null     object
 2   Age     10 non-null     int64
 3   Class   10 non-null     int64
 4   Gender  10 non-null     object
dtypes: int64(3), object(2)
memory usage: 528.0+ bytes

In [7]:
df.describe()

          Index        Age      Class
count  10.00000  10.000000  10.000000
mean    5.50000  14.300000   8.200000
std     3.02765   4.164666   2.097618
min     1.00000  10.000000   5.000000
25%     3.25000  12.250000   7.000000
50%     5.50000  13.500000   8.000000
75%     7.75000  14.750000   9.750000
max    10.00000  25.000000  12.000000

In [9]:
df.loc[3]

Index         4
Name      Bobby
Age          13
Class        12
Gender        M
Name: 3, dtype: object

In [10]:
df.isnull()

   Index   Name    Age  Class  Gender
0  False  False  False  False   False
1  False  False  False  False   False
2  False  False  False  False   False
3  False  False  False  False   False
4  False  False  False  False   False
5  False  False  False  False   False
6  False  False  False  False   False
7  False  False  False  False   False
8  False  False  False  False   False
9  False  False  False  False   False

**Task1**

In [21]:
data1={'Index':[1,2,3,4]
    ,'Name':['Paul','Palak','Jason','Bobby']
      ,'Age':[10,11,12,13],
      'Gender':['M','F','M','M'],
      }
df1= pd.DataFrame(data1)

In [22]:
df1

   Index   Name  Age Gender
0      1   Paul   10      M
1      2  Palak   11      F
2      3  Jason   12      M
3      4  Bobby   13      M

**Task2**

In [23]:
df1.columns=['Randomvalue 1','Randomvalue 2','Randomvalue 3','Randomvalue 4']

In [24]:
df1

   Randomvalue 1 Randomvalue 2  Randomvalue 3 Randomvalue 4
0              1          Paul             10             M
1              2         Palak             11             F
2              3         Jason             12             M
3              4         Bobby             13             M

**Task3**

In [25]:
df1.info

<bound method DataFrame.info of    Randomvalue 1 Randomvalue 2  Randomvalue 3 Randomvalue 4
0              1          Paul             10             M
1              2         Palak             11             F
2              3         Jason             12             M
3              4         Bobby             13             M>

In [26]:
df1.describe()

       Randomvalue 1  Randomvalue 3
count       4.000000       4.000000
mean        2.500000      11.500000
std         1.290994       1.290994
min         1.000000      10.000000
25%         1.750000      10.750000
50%         2.500000      11.500000
75%         3.250000      12.250000
max         4.000000      13.000000

**Task4**

In [27]:
df1.isnull().sum()

Randomvalue 1    0
Randomvalue 2    0
Randomvalue 3    0
Randomvalue 4    0
dtype: int64

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Randomvalue 1  4 non-null      int64
 1   Randomvalue 2  4 non-null      object
 2   Randomvalue 3  4 non-null      int64
 3   Randomvalue 4  4 non-null      object
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

**Task5**

In [29]:
df1.loc[0:4,'Randomvalue 2':'Randomvalue 3']

  Randomvalue 2  Randomvalue 3
0          Paul             10
1         Palak             11
2         Jason             12
3         Bobby             13

In [30]:
df1.iloc[0:4,1:3]

  Randomvalue 2  Randomvalue 3
0          Paul             10
1         Palak             11
2         Jason             12
3         Bobby             13